### ISSUE TITLE
After upgrading "Microsoft.Toolkit.Uwp.UI.Lottie 6.0.0", using "Windows App Cert Kit" general metadata correctness verification failed

### ISSUE THREAD

**Issue by KevinZjYang** [windows-toolkit/Lottie-Windows#214] opened 2019-12-24 05:36 UTC
## Describe the bug
This problem occurs whenever I upgrade "Microsoft.Toolkit.Uwp.UI.Lottie" to version 6.0.0. Downgrading to version 5.1.1 is all right.
See the error for details：[#2882](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2882)，Just like what @dpaulino said.
Because that issue has been closed.

XAML:
```
 <Border Background="Transparent"
               Visibility="{x:Bind IsLoading, Mode=OneWay}">
         <winui:AnimatedVisualPlayer>
                 <lottie:LottieVisualSource UriSource="ms-appx:///AnimatedVisuals/wave-loading.json" />
         </winui:AnimatedVisualPlayer>
 </Border>
```
- [ X] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:
Microsoft.Toolkit.Uwp.UI.Lottie 5.1.1 work.

## Steps to Reproduce
1. Upgrade "Microsoft.Toolkit.Uwp.UI.Lottie" to version 6.0.0
2. Create application package.
3. Test with Windows App Cert Kit.

## Expected behavior
```
 <TEST INDEX="58" NAME="一般元数据正确性" DESCRIPTION="元数据文件必须满足各种要求才是有效且正确的。" EXECUTIONTIME="00h:00m:09s.58ms" OPTIONAL="FALSE">
        <MESSAGES>
          <MESSAGE TEXT="文件 C:\Program Files\WindowsApps\8541KevinYang.28001B9000CE5_3.3.2.0_x64__z7y9f6aw0qfg2\Microsoft.Toolkit.Uwp.UI.Lottie.winmd 中类型为 Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass 的方法 add_AnimatedVisualInvalidated 的参数 value 引用了非 Windows 运行时类型 Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource。Windows 运行时类型仅可引用 Windows 运行时类型。" />
          <MESSAGE TEXT="未找到文件 C:\Program Files\WindowsApps\8541KevinYang.28001B9000CE5_3.3.2.0_x64__z7y9f6aw0qfg2\Microsoft.Toolkit.Uwp.UI.Lottie.winmd 中由类型 Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass 引用的类型 Microsoft.UI.Xaml.Controls.IAnimatedVisual。元数据文件中引用的所有类型都必须是可检测到的。" />
          <MESSAGE TEXT="文件 C:\Program Files\WindowsApps\8541KevinYang.28001B9000CE5_3.3.2.0_x64__z7y9f6aw0qfg2\Microsoft.Toolkit.Uwp.UI.Lottie.winmd 中类型为 Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource 的方法 add_AnimatedVisualInvalidated 的参数 value 引用了非 Windows 运行时类型 Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource。Windows 运行时类型仅可引用 Windows 运行时类型。" />
          <MESSAGE TEXT="未找到文件 C:\Program Files\WindowsApps\8541KevinYang.28001B9000CE5_3.3.2.0_x64__z7y9f6aw0qfg2\Microsoft.Toolkit.Uwp.UI.Lottie.winmd 中由类型 Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource 引用的类型 Microsoft.UI.Xaml.Controls.IAnimatedVisual。元数据文件中引用的所有类型都必须是可检测到的。" />
        </MESSAGES>
        <RESULT><![CDATA[FAIL]]></RESULT>
      </TEST>
```

## Screenshots
![批注 2019-12-24 133513](https://user-images.githubusercontent.com/31529584/71395757-4aa93b80-2652-11ea-92b1-77e5b2fe70f6.png)

## Environment
```
NuGet Package(s): 
Microsoft.UI.Xaml 2.3.191211002
Microsoft.Toolkit.Uwp.UI.Lottie 6.0.0

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [x ] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

**Comment by michael-hawker** [comment] 2020-01-15 22:01
FYI @simeoncran

**Comment by KevinZjYang** [comment] 2020-02-18 06:21
So long unsolved,I finally decided to deprecate "Microsoft.Toolkit.Uwp.UI.Lottie".
Use "Lottie Viewer" to convert json to c # code. Use as follows.

![image](https://user-images.githubusercontent.com/31529584/74709367-f2f60d80-5259-11ea-8168-7363804dd3fc.png)

```
<winui:AnimatedVisualPlayer Width="200"  Height="160">
                    <animatedvisuals:WaveLoading />
</winui:AnimatedVisualPlayer>```

**Comment by simeoncran** [comment] 2020-05-28 17:14
@KevinZjYang sorry to see that this wasn't given attention back in January. Did you ever try submitting despite the WACK error? We've noticed that the WACK can give false positives that the store doesn't care about.

**Comment by jeremiethibeault** [comment] 2020-06-18 19:20
I'm having the same issue on my last store submission:
Target: 10.0.18362.0
Microsoft.Toolkit.Uwp.UI: 6.0.0
Microsoft.Toolkit.Uwp.UI.Lottie: 6.0.0

```
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
```

**Comment by MatFillion** [comment] 2020-06-18 19:46
@simeoncran the above post from @jeremiethibeault failed at the store submission, so it's not a false positive :/

Full code is available here https://github.com/unoplatform/uno.ch9

**Comment by simeoncran** [comment] 2020-06-18 23:08
Thanks @MatFillion  and @jeremiethibeault. We are looking into this and will report back here.

**Comment by simeoncran** [comment] 2020-06-19 18:39
@MatFillion  and @jeremiethibeault. I'm told that there are known issues with how VS2017 packaged NuGet metadata that would explain what you're seeing.

Can you upgrade to the latest VS2019?

**Comment by jeremiethibeault** [comment] 2020-06-19 20:03
Hey @simeoncran, I'm using VS2019 16.5.1. Not sure if the issue should still be applicable on this version. I can try on the latest version to see if it fixes the issue. Let me know if there is anything else I can try. I will also check the local WACK test result if I see the same error message, would be easier to debug that.

Thanks!

**Comment by simeoncran** [comment] 2020-06-19 21:26
16.6.2 is the latest version. When I loaded your solution VS required that it first upgrade the projects. I wonder if that's a hint.

**Comment by jeremiethibeault** [comment] 2020-06-22 12:46
I was able to reproduce the issue locally on VS 16.6.2

I simply created the app bundles using the built-in publish feature of VS for UWP then I ran the WACK test locally which gave me the same result as on the store.

```
FAILED
General metadata correctness
Error Found: The general metadata correctness test detected the following errors:
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file C:\Program Files\WindowsApps\nventive.Ch9_1.0.6.0_x64__jc868da5z7jr4\Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file C:\Program Files\WindowsApps\nventive.Ch9_1.0.6.0_x64__jc868da5z7jr4\Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file C:\Program Files\WindowsApps\nventive.Ch9_1.0.6.0_x64__jc868da5z7jr4\Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file C:\Program Files\WindowsApps\nventive.Ch9_1.0.6.0_x64__jc868da5z7jr4\Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
Impact if not fixed: Microsoft store doesn't allow apps that don't pass Windows Runtime Metadata Validation.
How to fix: Please ensure that the compiler you are using to generate your Windows Runtime types is up to date with with the Windows Runtime specifications.
```

**Comment by simeoncran** [comment] 2020-06-22 15:37
We have a local repro now. I still don't understand what is triggering it, but we're tracking down the experts and will keep this thread updated.

**Comment by simeoncran** [comment] 2020-06-23 20:33
The issue is caused by the build not including Microsoft.UI.Xaml.winmd in the app package. You can check that by looking at the winmd files that get packaged into your .msix. As a result WACK doesn't find the references to IAnimatedVisualPlayer and IDynamicAnimatedVisualPlayer. We are looking into why that's happening.

**Comment by jeremiethibeault** [comment] 2020-06-25 11:42
@simeoncran That's interesting, I'm building MSIXUPLOAD files through Visual Studio > Publish > Create app packages (the app is associated to the Microsoft Store)

The package I've submitted to the store is the MSIXUPLOAD one.

![image](https://user-images.githubusercontent.com/5444226/85713398-533d0600-b6b7-11ea-8ee3-3e7ab1b9ac5c.png)

**Comment by jeremiethibeault** [comment] 2020-06-25 12:33
I confirmed that the Microsoft.UI.Xaml.winmd file is inside .msixupload > .msixbundle > x64.msix > WinMetadata

**Comment by simeoncran** [comment] 2020-06-25 14:08
Thank you, that's very helpful. Will keep you informed.

**Comment by ajbennet** [comment] 2020-07-02 17:04
Hi @jeremiethibeault, this issue is taking longer than expected. I don't want you to be blocked till we figure this out, so I had asked for an exception to this rule for your app (Uno Ch9) and the exception is in place now. Please try submitting the package and let us know if you re able to do so. I ll keep you posted as we make progress in the actual issue. Thank you for your patience.

**Comment by jeremiethibeault** [comment] 2020-07-07 14:17
Hey thanks @ajbennet, I submitted the app without the Lottie animation for now but I will take a look at resubmitting it with it.

Have a good day

**Comment by BenJKuhn** [comment] 2020-07-14 00:38
We've been investigating this issue. The root cause appears to be an issue in the certification tests. There's a mismatch between how the tools bundle metadata in store submission packages and how the tests search for that data, specifically in the case where metadata is provided by framework packages. I'm glad @ajbennet was able to provide a workaround while we determine how to fix this issue.

**Comment by matthewacme** [comment] 2020-07-15 20:17
It's still happening BTW

**Comment by simeoncran** [comment] 2020-07-20 18:01
@matthewacme  - can you give me some details and I'll see what I can do. No promises because I'm not really involved in the solution, but I can at least try to get your issue solved before this gets fixed for everyone.

**Comment by JaedsonBarbosa** [comment] 2020-08-09 20:03
I also have this problem here. Any news on when it will be resolved?

**Comment by matthewacme** [comment] 2020-08-10 12:50
@simeoncran 
I'm trying to submit MyRadar (both Ad and Ad-Free versions)

**Comment by RobbyRobbyRobby** [comment] 2020-08-11 05:16
Hi there,

I too am getting this issue, using Toolkit 6.1.0 in Visual Studio 2019.

If there is anything I can submit that would help, please let me know.

Rob.
Valley Software.


```
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file C:\Program Files\WindowsApps\xxxxxxx\Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.

The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file C:\Program Files\WindowsApps\xxxxxxx\Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file C:\Program Files\WindowsApps\xxxxxxx\Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.

The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file C:\Program Files\WindowsApps\xxxxxxx\Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
```

**Comment by michael-hawker** [comment] 2020-08-11 15:24
Hey everyone, wanted to post an update that we still have a thread open with the store team on this issue. There's a couple of things going on here related to how package metadata works and how framework packages are tested in the store.

In the meantime, I believe using [LottieGen](https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie-scenarios/getting_started_codegen) should work around this issue.

If you still need to dynamically consume json files, please let us know as well.

**Comment by under3415** [comment] 2020-09-07 05:35
Hi
Getting certification error on VS2019 (16.7.2) with Lottie 6.1.0

```
    Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file C:\Program Files\WindowsApps\XXXXXXXXXX\Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
    The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file C:\Program Files\WindowsApps\XXXXXXXXXX\Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
    Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file C:\Program Files\WindowsApps\XXXXXXXXXX\Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
    The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file C:\Program Files\WindowsApps\XXXXXXXXXX\Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
```

**Comment by under3415** [comment] 2020-09-16 20:44
Hi
Just to clarify, this is not just the certification tests, the Microsoft Store actually rejects the submission because of this error. 
Do we have a workaround or an ETA for resolution?

**Comment by nishitha-burman** [comment] 2020-09-25 18:49
Hi everyone,

Thank you for your patience as we investigated the issue. A solution is in the works for subsequent versions of WinUI (2.5 and later) but as a workaround you can do the following for now:

Open the .csproj or .vcxproj file that has a reference to the Lottie NuGet package and insert this target at the bottom of the file right before </Project>:
 
  ```
<Target Name="_AddXamlWinmdToPackageLayoutRoot" AfterTargets="_CreatePackageLayout">
    <Copy
        SourceFiles="@(_PackageLayoutFileSource)"
        DestinationFiles="@(_PackageLayoutFileSource->'$(AppxLayoutDir)%(Filename)%(Extension)')"
        Condition="'%(Filename)%(Extension)' == 'Microsoft.UI.Xaml.winmd'" />
  </Target>

``` 
Thank you

**Comment by simeoncran** [comment] 2020-09-25 19:20
Closing this issue as @nishitha-burman's workaround is the solution for existing projects. Please re-open if this doesn't work for you.

**Comment by under3415** [comment] 2020-09-27 01:17
> 
> 
> Hi everyone,
> 
> Thank you for your patience as we investigated the issue. A solution is in the works for subsequent versions of WinUI (2.5 and later) but as a workaround you can do the following for now:
> 
> Open the .csproj or .vcxproj file that has a reference to the Lottie NuGet package and insert this target at the bottom of the file right before :
>  
> 
> ```
> <Target Name="_AddXamlWinmdToPackageLayoutRoot" AfterTargets="_CreatePackageLayout">
>     <Copy
>         SourceFiles="@(_PackageLayoutFileSource)"
>         DestinationFiles="@(_PackageLayoutFileSource->'$(AppxLayoutDir)%(Filename)%(Extension)')"
>         Condition="'%(Filename)%(Extension)' == 'Microsoft.UI.Xaml.winmd'" />
> </Target>
> ```
> 

Thanks!

I can also confirm that using Microsft.UI.Xams version 2.5.0-prerelease.200812001 also fixed the issue.

**Comment by mentorfloat** [comment] 2020-10-05 09:34
@nishitha-burman , I am using XAML Island with a WPF App. I've added the `<Target>` at the bottom of my UWP .csproj right before `</Project>` but still failed the Windows Runtime Metadata Validation in a local WACK test.

```
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
```

I cannot try the 2.5.0-prerelease suggested by @under3415 because it will create 17 other Build errors in my case. An example from the 17 errors: 
`Payload file '...\WPF Base\bin\x86\Release\netcoreapp3.1\win-x86\Microsoft.UI.Xaml\DensityStyles\Compact.xaml' does not exist.` from Line 3036 in `...\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets`	

If I use the following NuGet packages, it will build but fail the metadata test as mentioned above:
Microsoft.UI.Xaml 2.4.3
Microsoft.Toolkit.Uwp.UI.Lottie 6.1.2
Microsoft.Toolkit.Win32.UI.XamlApplication 6.1.2
Microsoft.Toolkit.Wpf.UI.XamlHost 6.1.2

**Comment by nishitha-burman** [comment] 2020-12-08 00:13
@mentorfloat apologies for the delayed reply, were you able to resolve the issue?

**Comment by mentorfloat** [comment] 2020-12-08 23:00
No, I ended up removing Lottie entirely and instead created custom UserControl containing Key-Frame Animations.

**Comment by under3415** [comment] 2020-12-08 23:25
The issue was resolved in Microsoft.UI.XAML 2.5.0-prerelease.201202003, but has re-appeared in stable release v2.5.0 :-(

**Comment by nishitha-burman** [comment] 2020-12-09 20:34
Hi @under3415,

Does this issue appear in stable release v2.5.0  even with the workaround?

**Comment by under3415** [comment] 2020-12-09 21:44
> 
> 
> Hi @under3415,
> 
> Does this issue appear in stable release v2.5.0 even with the workaround?

Hi
Yes that is correct. 

It was working fine in pre-release without a workaround. 
Since updating to v.2.5.0 it is rejected from the store even with the workaround in place.

Regards
Dejan

**Comment by michael-hawker** [comment] 2020-12-09 22:51
@under3415 the WinUI pre-release and the release packages are built differently. FYT @ranjeshj

**Comment by under3415** [comment] 2020-12-09 23:02
If things are done differently for production release, doesn't that defy the purpose of pre-release testing?
D

**Comment by nishitha-burman** [comment] 2021-03-12 20:43
If you hit this issue while trying to publish your app please raise a support ticket on the store while we look into this issue. You can raise a ticket by doing the following:
1. Open a web browser to http://aka.ms/storesupport
2. Click "Contact Us"
3. Select "Dashboard - Store apps and games, Hardware, Collaborative"

Thank you!

**Comment by nishitha-burman** [comment] 2021-03-16 16:22
Fix is checked into the WinUI 2 repo, should be fixed in 2.6.

**Comment by rajeshangappan** [comment] 2021-04-12 10:34
After ugrading to latest version facing the below issue.
Exception thrown at 0x761EA8B2 :Microsoft C++ exception: winrt::hresult_error at memory location 0x09D3E9F8.

**Comment by nishitha-burman** [comment] 2021-04-12 17:54
Hi @rajeshangappan,

Thank you for reaching out. Which version of WinUI and Lottie are you in?

**Comment by under3415** [comment] 2021-04-13 22:14
Hi
This is again an issue with the latest versions of UI XAML and Lottie:

- Microsoft.UI.XAML 2.6.0-prerelease.210405001
- Microsoft.Toolkit.Uwp.UI.Lottie v7.0.2



```
    Error Found: The general metadata correctness test detected the following errors:

    Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
    The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
    Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
    The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.


```

**Comment by nishitha-burman** [comment] 2021-04-13 22:18
Hi @under3415, are you getting the same exception mentioned here https://github.com/windows-toolkit/Lottie-Windows/issues/214#issuecomment-817697637 when using the latest versions of UI XAML and Lottie?

**Comment by under3415** [comment] 2021-04-13 22:20
No, I am getting "metadata correctness test" error. I thought this bug is about that...

**Comment by nishitha-burman** [comment] 2021-04-13 22:25
Yes both https://github.com/windows-toolkit/Lottie-Windows/issues/405 and this issue are about the metadata correctness test. I was curious if you were also getting the issue mentioned here: https://github.com/windows-toolkit/Lottie-Windows/issues/214#issuecomment-817697637. Thanks for the clarification!

**Comment by under3415** [comment] 2021-04-13 22:28
I have also logged with with [WinUI.](https://github.com/microsoft/microsoft-ui-xaml/issues/3780) 

Do you understand what is going on here? The issue is fixed in one version, then regresses in the next!? It's happened twice already! It's really weird...

**Comment by eliezerpMS** [comment] 2021-04-14 00:38
@under3415. Sorry to hear that you are hitting this issue again. Looking at your post [here](https://github.com/microsoft/microsoft-ui-xaml/issues/3780#issuecomment-805178180) it looks like WACK was failing when you updated to Microsoft.UI.XAML 2.6.0-prerelease.210315002. When this happened what version of Lottie were you on? If you keep Lottie on the last version that passed WACK(please let us know which one that is) are you able to identify which versions of Microsoft.UI.XAML 2.6.0-prerelease caused you to fail WACK? 

Does the issue repro for you with the Lottie Sample app when using Microsoft.UI.XAML 2.6.0-prerelease.210405001 and Microsoft.Toolkit.Uwp.UI.Lottie v7.0.2. If not do you have a simple app you could share with us that repros this issue with these versions of Lottie and Microsoft.UI.XAML?

**Comment by under3415** [comment] 2021-04-14 00:49
Lottie version does not seem to matter, the issue is fixed and broken in WinUI:

2.5.0-prerelease.201202003  OK
2.5.0                                       Broken
2.6.0-prerelease.210227001  OK
2.6.0-prerelease.210405001  Broken

I'm raising it here as well as in WinUI as I am not sure who needs to fix this, and why is it regressing.

**Comment by under3415** [comment] 2021-04-14 01:52
This issue only happens when you try to submit to Microsoft Store on a "Non-flighted submission". 
It passes certification using the certification app and even the test flight in the store. 

So to replicate the issue, create an app using lottie and winui and submit to store as "Non-flighted submission".

**Comment by rajeshangappan** [comment] 2021-04-15 17:25
> Hi @rajeshangappan,
> 
> Thank you for reaching out. Which version of WinUI and Lottie are you using?

Lottie version:7.0.2, Microsoft.UI.Xaml:2.5.0

**Comment by nishitha-burman** [comment] 2021-07-02 15:36
Fixed by Microsoft.UI.XAML: https://github.com/microsoft/microsoft-ui-xaml/issues/3780

**Closed by nishitha-burman** 2021-07-02 15:36 UTC
